import * as fs from 'fs';
import * as path from 'path';

// --- Type Definitions for Analysis Report ---

/**
 * Analysis of a single choice within a Daml template.
 */
export interface ChoiceAnalysis {
    name: string;
    controllers: number;
    creates: number;
    archives: number;
    exercises: number;
    fetches: number;
    fetchesByKey: number;
    lookupsByKey: number;
    /** A heuristic score representing the computational and storage cost of this choice. */
    complexityScore: number;
}

/**
 * Analysis of a single Daml template.
 */
export interface TemplateAnalysis {
    templateName: string;
    filePath: string;
    signatories: number;
    observers: number;
    fieldCount: number;
    /** A rough estimate of the contract payload size in bytes. */
    estimatedPayloadBytes: number;
    choices: ChoiceAnalysis[];
    /** A heuristic score representing the cost of creating an instance of this template. */
    complexityScore: number;
}

/**
 * The final report generated by analyzing a Daml project.
 */
export interface AnalysisReport {
    templates: TemplateAnalysis[];
    /** The sum of complexity scores for all templates, representing a rough project-wide complexity. */
    totalComplexityScore: number;
    warnings: string[];
}


// --- Constants for Complexity Calculation ---

/**
 * Heuristic weights for various Daml operations. These are designed to be
 * representative of relative costs on a DLT platform like Canton.
 * Higher values indicate more expensive operations.
 */
const WEIGHTS = {
    // Contract creation costs
    SIGNATORY: 10,
    OBSERVER: 5,
    FIELD_BASE: 1,
    FIELD_PER_BYTE: 0.1,

    // Choice execution costs
    CHOICE_BASE: 5,
    CONTROLLER: 2,
    CREATE: 15,
    ARCHIVE: 5,
    EXERCISE: 20,
    FETCH: 2,
    FETCH_BY_KEY: 8,
    LOOKUP_BY_KEY: 8,
};

/**
 * Rough estimates for Daml type sizes in bytes. Used for payload size calculation.
 */
const TYPE_SIZE_ESTIMATES: { [key: string]: number } = {
    'Int': 8,
    'Decimal': 16,
    'Text': 32,      // Average size assumption
    'Party': 32,     // Party identifiers can be long text strings
    'Bool': 1,
    'Date': 4,
    'Time': 8,
    'ContractId': 48, // TemplateId + hash
    'Optional': 4,   // Overhead for the wrapper
    '[]': 8,         // Overhead for a list
};

/**
 * Estimates the size of a Daml type based on heuristics.
 * @param typeStr A string representing the Daml type (e.g., "Text", "Optional Party").
 * @returns An estimated size in bytes.
 */
function estimateTypeSize(typeStr: string): number {
    const type = typeStr.trim();
    if (type.startsWith('Optional')) {
        const innerType = type.replace('Optional', '').trim();
        return TYPE_SIZE_ESTIMATES['Optional'] + estimateTypeSize(innerType);
    }
    if (type.startsWith('[')) {
        const innerType = type.replace(/[\[\]]/g, '').trim();
        // Assume one element for estimation; a more advanced analyzer could parse list literals.
        return TYPE_SIZE_ESTIMATES['[]'] + estimateTypeSize(innerType);
    }
    return TYPE_SIZE_ESTIMATES[type] || 32; // Default to 32 bytes for unknown/complex types
}

/**
 * Analyzes the content of a single Daml file.
 * @param fileContent The string content of the .daml file.
 * @param filePath The path to the file for reporting purposes.
 * @returns An array of TemplateAnalysis objects found in the file.
 */
function analyzeDamlContent(fileContent: string, filePath: string): TemplateAnalysis[] {
    const templates: TemplateAnalysis[] = [];
    // This regex finds the start of a template definition.
    const templateRegex = /^\s*template\s+([A-Za-z0-9_]+)\s*\n\s+with/gm;
    let match;

    while ((match = templateRegex.exec(fileContent)) !== null) {
        const templateName = match[1];
        const templateStartIndex = match.index;

        // Heuristically determine the end of the template block.
        // It ends at the next `template` keyword or the end of the file.
        const nextTemplateMatch = /^\s*template\s/gm.exec(fileContent.substring(templateStartIndex + match[0].length));
        const templateEndIndex = nextTemplateMatch
            ? templateStartIndex + match[0].length + nextTemplateMatch.index
            : fileContent.length;

        const templateBody = fileContent.substring(templateStartIndex, templateEndIndex);
        
        const analysis = analyzeTemplateBody(templateBody, templateName, filePath);
        templates.push(analysis);
    }
    return templates;
}

/**
 * Performs a detailed analysis of a single template's source code.
 * @param body The source code string of the template.
 * @param templateName The name of the template.
 * @param filePath The file path where the template is defined.
 * @returns A TemplateAnalysis object.
 */
function analyzeTemplateBody(body: string, templateName: string, filePath: string): TemplateAnalysis {
    // --- Field Analysis ---
    const withBlockMatch = body.match(/\s+with\n([\s\S]*?)\s+where/);
    let fieldCount = 0;
    let estimatedPayloadBytes = 0;
    if (withBlockMatch && withBlockMatch[1]) {
        const fieldsBlock = withBlockMatch[1];
        const fieldLines = fieldsBlock.split('\n').filter(line => line.trim().includes(':'));
        fieldCount = fieldLines.length;
        fieldLines.forEach(line => {
            const parts = line.split(':');
            if (parts.length > 1) {
                const type = parts[1].trim().split(' ')[0];
                estimatedPayloadBytes += estimateTypeSize(type);
            }
        });
    }

    // --- Stakeholder & Choice Analysis ---
    const whereBlockMatch = body.match(/\s+where\n([\s\S]*)/);
    const whereBlock = whereBlockMatch ? whereBlockMatch[1] : "";

    const countParties = (text: string | undefined) => text ? (text.split(/\s+/).filter(p => p.length > 0)).length : 0;

    const signatoryMatch = whereBlock.match(/^\s*signatory\s+(.*?)\n/m);
    const signatories = countParties(signatoryMatch?.[1]);

    const observerMatch = whereBlock.match(/^\s*observer\s+(.*?)\n/m);
    const observers = countParties(observerMatch?.[1]);

    const choices: ChoiceAnalysis[] = [];
    const choiceRegex = /choice\s+([A-Za-z0-9_]+)\s*:[\s\S]*?\s+controller\s+([\s\S]*?)\s+do([\s\S]*?)(?=\n\s*choice|\n\s*(?:ensure|key))/g;
    let choiceMatch;

    while ((choiceMatch = choiceRegex.exec(whereBlock)) !== null) {
        const choiceName = choiceMatch[1];
        const controllersText = choiceMatch[2];
        const choiceBody = choiceMatch[3];

        const controllers = countParties(controllersText);
        const creates = (choiceBody.match(/\bcreate\b/g) || []).length;
        const archives = (choiceBody.match(/\barchive\b/g) || []).length;
        const exercises = (choiceBody.match(/\bexercise\b/g) || []).length;
        const fetches = (choiceBody.match(/\bfetch\b/g) || []).length;
        const fetchesByKey = (choiceBody.match(/\bfetchByKey\b/g) || []).length;
        const lookupsByKey = (choiceBody.match(/\blookupByKey\b/g) || []).length;

        let choiceScore = WEIGHTS.CHOICE_BASE;
        choiceScore += controllers * WEIGHTS.CONTROLLER;
        choiceScore += creates * WEIGHTS.CREATE;
        choiceScore += archives * WEIGHTS.ARCHIVE;
        choiceScore += exercises * WEIGHTS.EXERCISE;
        choiceScore += fetches * WEIGHTS.FETCH;
        choiceScore += fetchesByKey * WEIGHTS.FETCH_BY_KEY;
        choiceScore += lookupsByKey * WEIGHTS.LOOKUP_BY_KEY;

        choices.push({
            name: choiceName,
            controllers,
            creates,
            archives,
            exercises,
            fetches,
            fetchesByKey,
            lookupsByKey,
            complexityScore: Math.round(choiceScore)
        });
    }

    let templateScore = 0;
    templateScore += signatories * WEIGHTS.SIGNATORY;
    templateScore += observers * WEIGHTS.OBSERVER;
    templateScore += fieldCount * WEIGHTS.FIELD_BASE;
    templateScore += estimatedPayloadBytes * WEIGHTS.FIELD_PER_BYTE;
    
    return {
        templateName,
        filePath,
        signatories,
        observers,
        fieldCount,
        estimatedPayloadBytes: Math.round(estimatedPayloadBytes),
        choices,
        complexityScore: Math.round(templateScore),
    };
}

/**
 * Recursively finds all .daml files in a directory.
 * @param dir The directory to search.
 * @returns An array of full file paths.
 */
function findDamlFiles(dir: string): string[] {
    let damlFiles: string[] = [];
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            damlFiles = damlFiles.concat(findDamlFiles(fullPath));
        } else if (path.extname(entry.name) === '.daml') {
            damlFiles.push(fullPath);
        }
    }
    return damlFiles;
}

/**
 * Analyzes a Daml project by parsing its .daml source files.
 * @param projectRoot The root directory of the Daml project (containing `daml.yaml`).
 * @returns A comprehensive analysis report.
 * @throws An error if the `daml` source directory cannot be found.
 */
export function analyzeProject(projectRoot: string): AnalysisReport {
    const damlSourcePath = path.join(projectRoot, 'daml');
    if (!fs.existsSync(damlSourcePath)) {
        throw new Error(`Daml source directory not found at: ${damlSourcePath}`);
    }

    const damlFiles = findDamlFiles(damlSourcePath);
    const allTemplates: TemplateAnalysis[] = [];
    const warnings: string[] = [];

    for (const file of damlFiles) {
        try {
            const content = fs.readFileSync(file, 'utf-8');
            const templatesInFile = analyzeDamlContent(content, path.relative(projectRoot, file));
            allTemplates.push(...templatesInFile);
        } catch (error) {
            const errorMessage = error instanceof Error ? error.message : String(error);
            warnings.push(`Failed to parse ${file}: ${errorMessage}`);
        }
    }

    const totalComplexityScore = allTemplates.reduce((acc, t) => {
        const choicesScore = t.choices.reduce((sum, c) => sum + c.complexityScore, 0);
        return acc + t.complexityScore + choicesScore;
    }, 0);

    return {
        templates: allTemplates,
        totalComplexityScore,
        warnings
    };
}